---

- hosts: all
  sudo: yes
  tasks:
    - apt: name=redis-server state=present
    - apt: name=python-redis state=present

      # Setup additional development tools
    - apt: name=vim state=present
    - apt: name=tmux state=present
    - apt: name=htop state=present
    #- apt: name=python-virtualenv state=present
    #- apt: name=virtualenvwrapper state=present
    - apt: name=ipython state=present
    - apt: name=python-pudb state=present
    - apt: name=python-pip state=present
    - apt: name=python-mysqldb state=present
    - apt: name=jq state=present
    - shell: pip install -U pip
    - shell: pip install docker-py==1.1.0
    - shell: pip install python-keystoneclient==1.5.0

    - shell: pip install httpie
    # Graph drawing
    #- apt: name=python-matplotlib state=present
    - apt: name=python-pygraphviz state=present

      # Setup development env for solar
    - shell: python setup.py develop chdir=/vagrant/solar
