---

- hosts: all
  sudo: yes
  tasks:
    - apt: name=git state=present
    - apt: name=python-mock state=present
    - apt: name=python-keystoneclient state=present

    # PIP
    - apt: name=python-pip state=absent
    - apt: name=python-six state=absent
    - shell: easy_install pip
    - shell: pip install -U pip
    - shell: pip install -U setuptools
    - shell: pip install httpie
    - shell: pip install docker-py==1.1.0

    # Redis
    - apt: name=redis-server state=present
    - shell: pip install redis
    - lineinfile: dest=/etc/redis/redis.conf regexp='^bind ' line='bind 0.0.0.0'
    - service: name=redis-server state=restarted

    # Puppet
    - shell: wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb -O /root/puppetlabs-release-trusty.deb
    - shell: dpkg -i /root/puppetlabs-release-trusty.deb
    - shell: apt-get update

    - apt: name=puppet state=present
    - git: repo=https://github.com/CGenie/hiera-redis dest=/root/hiera-redis
    - shell: gem build hiera-redis.gemspec && gem install hiera-redis-3.0.0.gem chdir=/root/hiera-redis
    - template: src=/vagrant/hiera.yaml dest=/etc/puppet/hiera.yaml
    - file: path=/etc/puppet/hieradata state=directory
    # Make paths puppet 4 compatible
    - file: path=/etc/puppetlabs/code/ state=directory
    - file: src=/etc/puppet/hiera.yaml dest=/etc/puppetlabs/code/hiera.yaml state=link
    - apt: name=ruby-dev state=present
    - file: path=/var/tmp/puppet/modules state=directory owner=puppet
    - file: path=/var/tmp/puppet/Puppetfile state=touch owner=puppet
    - file: path=/etc/puppet/modules state=absent
    - file: path=/etc/puppetlabs/code/modules state=absent
    - file: path=/etc/puppetlabs/code/hieradata state=absent
    - file: src=/var/tmp/puppet/modules dest=/etc/puppet/modules state=link
    - file: src=/var/tmp/puppet/modules dest=/etc/puppetlabs/code/modules state=link
    - file: src=/etc/puppet/hieradata dest=/etc/puppetlabs/code/hieradata state=link
    - shell: gem install librarian-puppet --no-ri --no-rdoc

      # Setup additional development tools
    - name: Additional development tools
      apt: name={{ item }} state=present
      with_items:
      - vim
      - tmux
      - htop
      - python-mysqldb
      - jq
      - ipython
      - python-pudb

    # Graph drawing
    #- apt: name=python-matplotlib state=present
    - apt: name=python-pygraphviz state=present
    #- shell: pip install pygraphviz

      # Setup development env for solar
    - shell: python setup.py develop chdir=/vagrant/solar

    # Ubuntu OpenStack packages
    #- apt: name=ubuntu-cloud-keyring state=present
    #- shell: echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/kilo main" > /etc/apt/sources.list.d/cloudarchive-kilo.list
    #- shell: echo "deb http://osci-mirror-poz.infra.mirantis.net/pkgs/ubuntu-2015-06-25-194717 trusty-updates main" > /etc/apt/sources.list.d/fuel-kilo.list
    #- shell: echo "deb http://osci-mirror-poz.infra.mirantis.net/pkgs/ubuntu-latest trusty main" > /etc/apt/sources.list.d/fuel-kilo.list
    # cloudarchive key
    #- shell: apt-key adv --recv-key --keyserver keyserver.ubuntu.com 5EDB1B62EC4926EA
    # some other keys
    #- shell: apt-key adv --recv-key --keyserver keyserver.ubuntu.com 9D6D8F6BC857C906
    #- shell: apt-key adv --recv-key --keyserver keyserver.ubuntu.com 7638D0442B90D010
    # mirantis poznan
    #- shell: apt-key adv --recv-key --keyserver keyserver.ubuntu.com 40976EAF437D05B5
    #- shell: apt-key adv --recv-key --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
    #- shell: apt-get update
