---

- hosts: all
  sudo: yes
  tasks:
    - apt: name=redis-server state=present
    - apt: name=python-redis state=present
    - lineinfile: dest=/etc/redis/redis.conf regexp='^bind ' line='bind 0.0.0.0'

    - apt: name=git state=present

    - apt: name=puppet state=present
    - git: repo=https://github.com/CGenie/hiera-redis dest=/root/hiera-redis
    - shell: gem build hiera-redis.gemspec && gem install hiera-redis-1.0.2.gem chdir=/root/hiera-redis
    - template: src=/vagrant/hiera.yaml dest=/etc/puppet/hiera.yaml
    - file: path=/etc/puppet/hieradata state=directory

      # Setup additional development tools
    - apt: name=vim state=present
    - apt: name=tmux state=present
    - apt: name=htop state=present
    #- apt: name=python-virtualenv state=present
    #- apt: name=virtualenvwrapper state=present
    - apt: name=ipython state=present
    - apt: name=python-pudb state=present
    #- apt: name=python-pip state=present
    - shell: easy_install pip
    - apt: name=python-mysqldb state=present
    - apt: name=jq state=present
    - shell: pip install -U pip
    - shell: pip install docker-py==1.1.0
    - shell: pip install python-keystoneclient==1.5.0

    - shell: pip install httpie
    # Graph drawing
    #- apt: name=python-matplotlib state=present
    - apt: name=python-pygraphviz state=present

      # Setup development env for solar
    - shell: python setup.py develop chdir=/vagrant/solar
