---

- hosts: all
  sudo: yes
  tasks:
    - shell: docker --version
      ignore_errors: true
      register: docker_version
    - shell: curl -sSL https://get.docker.com/ | sudo sh
      when: docker_version | failed
    - shell: docker pull debian:jessie
      # Setup additional development tools
    - apt: name=vim state=present
    - apt: name=tmux state=present
    - apt: name=htop state=present
    - apt: name=python-virtualenv state=present
    - apt: name=virtualenvwrapper state=present
    - apt: name=ipython state=present
      # Setup development env for solar
    - shell: python setup.py develop chdir=/vagrant/solar
