
- hosts: [master, slave1]
  sudo: yes
  vars:
    mistral_conf: /etc/mistral.conf
    rabbitmq_host: 10.0.0.2
  tasks:
    - shell: apt-get install -y python-dev python-setuptools libffi-dev libxslt1-dev libxml2-dev libyaml-dev libssl-dev crudini
    - shell: cd /srv/mistral/ && git branch
      ignore_errors: true
      register: check_mistral
    - git: repo=https://github.com/openstack/mistral.git
           dest=/srv/mistral
           version=stable/kilo
      when: check_mistral | failed
    - shell: cp /srv/mistral/etc/mistral.conf.sample {{mistral_conf}}
    - shell: crudini --set /etc/mistral.conf pecan auth_enable false
    - shell: hostname
      register: hostname
    - shell: crudini --set {{mistral_conf}} {{item}} hostname {{hostname.stdout}}
      with_items:
        - engine
        - executor
    - shell: crudini --set {{mistral_conf}} oslo_messaging_rabbit rabbitmq_host
        {{rabbitmq_host}}
    - shell: python setup.py install
             chdir=/srv/mistral
- hosts: [master]
  sudo: yes
  vars:
    mistral_conf: /etc/mistral.conf
  tasks:
    - shell: python tools/sync_db.py --config-file {{mistral_conf}}
             chdir=/srv/mistral
    - shell: pip install python-mistralclient
    - shell: pgrep mistral-server
      ignore_errors: true
      register: mistral
    - shell: nohup mistral-server --server api,engine,executor --config-file {{mistral_conf}} &
      tags:
        - run
      when: mistral | failed

- hosts: [slave1]
  sudo: yes
  vars:
    mistral_conf: /etc/mistral.conf
  tasks:
    - shell: pgrep mistral-server
      ignore_errors: true
      register: mistral
    - shell: nohup mistral-server --server executor --config-file {{mistral_conf}} &
      tags:
        - run
      when: mistral | failed


