# HAProxy deployment with MariaDB, Keystone and Nova

workdir: /vagrant
resource-save-path: rs/
#test-suite: haproxy_deployment.haproxy_deployment

resources:
  - name: node1
    model: x/resources/ro_node/
    args:
      ip: 10.0.0.3
      ssh_key: /vagrant/.vagrant/machines/solar-dev2/virtualbox/private_key
      ssh_user: vagrant

  - name: keystone1
    model: x/resources/keystone/
    args:
      ip:
      image: TEST
      ssh_user:
      ssh_key:

  - name: haproxy_keystone_config
    model: x/resources/haproxy_config/
    args:
      listen_port: 5000
      ports: {}
      servers: {}


connections:
  - emitter: node1
    receiver: keystone1

  # Multiple subscription test
  - emitter: node1
    receiver: keystone1

  - emitter: keystone1
    receiver: haproxy_keystone_config
    mapping:
      ip: servers
      port: ports
