- hosts: [{{ ip }}]
  sudo: yes
  tasks:
    - name: keystone container
      docker:
        name: {{ name }}
        image: {{ image }}
        state: running
        ports:
        - {{ port }}:5000
        - {{ admin_port }}:35357
        volumes:
        - {{ config_dir }}:/etc/keystone
