- hosts: [{{ ip }}]
  sudo: yes
  tasks:
    - file: path={{config_dir}} state=directory
    - template: src={{resource_dir}}/templates/keystone.conf dest={{config_dir}}/keystone.conf
    - template: src={{resource_dir}}/templates/default_catalog.templates dest={{config_dir}}/default_catalog.templates
    - template: src={{resource_dir}}/templates/logging.conf dest={{config_dir}}/logging.conf
    - template: src={{resource_dir}}/templates/policy.json dest={{config_dir}}/policy.json
    - template: src={{resource_dir}}/templates/exports dest={{ config_dir }}/keystone-exports
    - name: keystone container
      docker:
        command: /bin/bash -c "keystone-manage db_sync && /usr/bin/keystone-all"
        name: {{ resource_name }}
        image: {{ image }}
        state: running
        expose:
        - 5000
        - 35357
        ports:
        - {{ port }}:5000
        - {{ admin_port }}:35357
        volumes:
        - {{ config_dir }}:/etc/keystone
    - name: wait for keystone
      wait_for: host={{ip}} port={{port}} timeout=20
