id: keystone_base_config
handler: none
version: 1.0.0

input:
    admin_token:
      schema: str!
      value: admin
    db_password:
      schema: str!
      value: password
    db_user:
      schema: str!
      value: keystone
    db_host:
      schema: str!
      value:
    db_port:
      schema: int!
      value:
    db_name:
      schema: str!
      value: keystone

tags: [resource/keystone_base_config, resources/keystone]
