id: mariadb_user
handler: ansible
version: 1.0.0
actions:
    run: run.yml
    remove: remove.yml
input:
    password:
    db:
    login_password:
    login_port:
    login_user:
    ip: 
    ssh_key: 
    ssh_user: 
