id: haproxy
handler: ansible
version: 1.0.0
input:
    ip:
    config_dir: /etc/haproxy
    configs:
    configs_ports:
    ssh_user:
    ssh_key:
input-types:
    configs: list
    configs_ports: list
