# TODO
- hosts: [{{ ip }}]
  sudo: yes
  vars:
    config_dir: {src: {{ config_dir['src'] }}, dst: {{ config_dir['dst'] }}}
    haproxy_ip: {{ ip }}
    haproxy_services:
      {% for service, servers, ports, port in zip(configs_names, configs, configs_ports, listen_ports) %}
      - name: {{ service }}
        listen_port: {{ port }}
        servers:
          {% for server_ip, server_port in zip(servers, ports) %}
          - name: {{ name }}
            ip: {{ server_ip }}
            port: {{ server_port }}
          {% endfor %}
      {% endfor %}
  tasks:
    - apt: name=python-pip state=present
    - shell: pip install docker-py
    - service: name=docker state=started
    - file: path={{ config_dir['src'] }}/ state=directory
    - file: path={{ config_dir['src'] }}/haproxy.cfg state=touch
    - template: src=/vagrant/haproxy.cfg dest={{ config_dir['src'] }}/haproxy.cfg
