
- hosts: [{{ ip }}]
  sudo: yes
  tasks:
    - apt: name=python-pip state=present
    - shell: pip install docker-py
    - service: name=docker state=started
    - docker:
       name: {{ name }}
       image: {{ image }}
       state: running
       ports:
         {% for name, port in ports.items() %}
         # {{ name }}
         - {{ port }}:{{ port }}
         {% endfor %}
       volumes:
         # TODO: host_binds might need more work
         # Currently it's not that trivial to pass custom src: dst here
         # (when a config variable is passed here from other resource)
         # so we mount it to the same directory as on host
         {% for emitter, bind in host_binds.items() %}
         - {{ bind }}:{{ bind }}
         {% endfor %}
